/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example


fun main() {

    val a = 5
    val b = 3 
    val c = 9

    if (a < 0 && a > 0){
        println("a no puede ser = a 0")
    }
    
    println("La funcion es ${a}x² + ${b}x + ${c}")
}
