/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

// Definición de constantes para los coeficientes de la función cuadrática
const val A = 2
const val B = 3
const val C = 1

// Función para calcular los valores de Y en el rango de x = -5 a x = 5
fun calcular(a: Int, b: Int, c: Int) {
    println("Valores de la función cuadrática:")
    for (x in -5..5) {
        val resultado = a * x * x + b * x + c
        println("x = $x → y = $resultado")
    }
    println(".--------------------------------------------.")
}

// Función para calcular el discriminante y las raíces
fun raiz(a: Int, b: Int, c: Int) {
    val discriminante = b * b - 4 * a * c
    println(" Discriminante: $discriminante")

    when {
        discriminante > 0 -> {
            val raiz1 = (-b + Math.sqrt(discriminante.toDouble())) / (2 * a)
            val raiz2 = (-b - Math.sqrt(discriminante.toDouble())) / (2 * a)
            println("Dos raíces reales distintas:")
            println("x1 = ${"%.2f".format(raiz1)}")
            println("x2 = ${"%.2f".format(raiz2)}")
        }
        discriminante == 0 -> {
            val raiz = -b / (2.0 * a)
            println(" Una raíz real doble:")
            println("x = ${"%.2f".format(raiz)}")
        }
        else -> {
            println(" No hay raíces reales (discriminante negativo).")
        }
    }

    println(".--------------------------------------------.")
}

// Función principal
fun main() {
    println(" Función cuadrática: ${A}x² + ${B}x + ${C}")
    println(".--------------------------------------------.")

    calcular(A, B, C)
    raiz(A, B, C)
}
