/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

fun calcular(a: Int, b: Int, c: Int) {
    for (x in -5..5) {
        val resultado = a * x * x + b * x + c
        println("Y = $resultado")
    }
}

fun raiz(a: Int, b: Int, c: Int) {
    val discriminante = b * b - 4 * a * c
    println("La discriminante es: $discriminante")
    println(".                                    .")

    val raiz1 = (-b + Math.sqrt(discriminante.toDouble())) / (2 * a)
    val raiz2 = (-b - Math.sqrt(discriminante.toDouble())) / (2 * a)

    println("x1: ${"%.2f".format(raiz1)}")
    println("x2: ${"%.2f".format(raiz2)}")
}


fun main() {
    val a = 2
    val b = 3
    val c = 1

    if (a == 0) {
        println("a no puede ser = a 0")
        return
    }

    println("La función es ${a}x² + ${b}x + ${c}")
    println(".                                    .")

    calcular(a, b, c)
    println(".                                    .")

    raiz(a, b, c)
}
